### ISSUE TITLE
Support for Metal / M1 Processors?

### ISSUE THREAD

**Issue by danktec** [fruitz-of-dojo/Quake#3]
The game starts and renders OK but the keyboard and mouse are completely disabled. Cannot exit the game or exit full-screen mode. Machine needs to be rebooted to exit ;(

update: Turns out accessibility permissions were not properly set for the application. seems to work well now ;)

update2: GLQuake seems to unexpectedly crash on selecting "new game". Only occurs sometimes.

**Comment by shamilovtim** [comment]
@dhdanno There are a number of clients that are actively supported and one that even uses Vulkan and hence should compile natively to Metal.

VkQuake: Quake on Vulkan (Should have Metal support). https://github.com/Novum/vkQuake
QuakeSpasm: Quake on SDL2 (OpenGL / actively maintained). http://quakespasm.sourceforge.net/
MarkV: Quake on SDL (OpenGL): http://quakeone.com/markv/.

All of these projects supersede this one. QuakeSpasm is the most popular but VkQuake is probably what you're looking for. Also, this is where all of the engine developers hang out and could point you in the right direction: https://celephais.net/board/forum.php. Good luck!
